name: Terraform GitHub Actions

on: push

jobs:
  terraform:
    name: Terraform Init
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETE_ID }}
      AWS_REGION: "eu-west-1"
